# Generated by Django 5.2.6 on 2025-09-19 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='person_id',
        ),
    ]
